version: 2

sources:
  - name: olist_raw
    schema: RAW
    tables:
      - name: customers
        identifier: customers
        loaded_at_field: customer_id
      - name: orders
        identifier: orders
        loaded_at_field: order_purchase_timestamp
        freshness:
          warn_after:
            count: 2600
            period: day
          error_after:
            count: 2700
            period: day
      - name: order_items
        identifier: order_items
        loaded_at_field: order_id
      - name: products
        identifier: products
      - name: payments
        identifier: payments
      - name: products_with_categories
        identifier: products_with_categories